---
title: "Reading list sociology"
author: "Thom Volker"
date: "2/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Reading list

- [ ] Bolton et al., 2004; Bolton & Ockenfels, 2009 (in Trust in triads (2010); assign subjects to either dyadic or network embeddedness conditions).

- [ ] Barrera, D., Buskens, V., 2009. Third-party effects. In: Cook, K.S., Snijders, C., Buskens, V., Cheshire, C. (Eds.), eTrust. Forming Relationships in the Online World. Russell Sage, New York, pp. 37–72.

Only laboratory experiment in which both dyadic and network embeddedness were manipulated in Trust Games in similar ways to the triadic repeated Trust Game article by Buskens, Raub and Van der Veer. This experiment however involves a more complex setting in which trustors play simultaneously rather than sequentially with one trustee, which affects the predictions.

- [ ] Bolton, G.E., Katok, E., Ockenfels, A., 2004. How effective are online reputation mechanisms? An experimental study. Management Science 50, 1587–1602.

Repeated Trust Games with dyadic and network embeddedness.

- [ ] Bolton, G.E., Ockenfels, A., 2009. The limits of trusts in economic transactions: investigations of perfect reputation systems. In: Cook, K.S., Snijders, C., Buskens, V., Cheshire, C. (Eds.), eTrust. Forming Relationships in the Online World. Russell Sage, New York, pp. 15–36.

Repeated Trust Games with dyadic and network embeddedness.

- [ ] Casella, Alessandra, Navin Kartik, Luis Sanchez, and Sébastien Turban. 2018. “Communication in Context: Interpreting Promises in an Experiment on Competition and Trust.” Proceedings of the National Academy of Sciences 115, no. 5: 933–938.

Overview of cooperation in networks.

- [ ] Sánchez, Angel. 2018. “Physics of Human Cooperation: Experimental Evidence and Theoretical Models.” Journal of Statistical Mechanics: Theory and Experiment 2018, no. 2: 024001.

Overview of cooperation in networks.

- [ ] Wang, J., Suri, S., & Watts, D. J. (2012). Cooperation and assortativity with dynamic partner updating. Proceedings of the National Academy of Sciences, 109(36), 14363-14368.

Cooperation due to dynamic partner updating?

- [ ] Kollock, P. (1998). Social dilemmas: The anatomy of cooperation. Annual Review of Sociology, 24, 183-214.

Annual review on cooperation.

- [ ] Fehr, E., & Gintis, H. (2007). Human motivation and social cooperation: Experimental and analytical foundations. Annual Review of Sociology, 33.

Annual review on cooperation.

- [ ] Simpson, B., & Willer, R. (2015). Beyond altruism: Sociological foundations of cooperation and prosocial behavior. Annual Review of Sociology, 41.

Annual review on cooperation.

- [ ] Macy, M. W., & Flache, A. (1995). Beyond rationality in models of choice. Annual Review of Sociology, 21.

Moving beyond RCT in sociology?

- [ ] Kroneberg, C., & Kalter, F. (2012). Rational choice theory and empirical research: Methodological and theoretical contributions in Europe. Annual Review of Sociology, 38, 73-92.

Overview of rational choice theory in sociological research.

- [ ] Edling, C. R. (2002). Mathematics in sociology. Annual Review of Sociology, 28.

See title.

- [ ] Hechter, M., & Kanazawa, S. (1997). Sociological rational choice theory. Annual Review of Sociology, 23.

See title.

- [ ] Udehn, L. (2002). The changing face of methodological individualism. Annual Review of Sociology, 28.

See title.

- [ ] Macy, M. W., & Willer, R. (2002). From factors to actors: Computational sociology and agent-based modeling. Annual Review of Sociology, 28.

See title.

- [ ] Spillman, L., & Strand, M. (2013). Interest-oriented action. Annual Review of Sociology, 39, 85-104.

See title.

# Dyadic embeddedness

## Control - endogenous

## Control - exogenous

# Network embeddedness

### Studies that found an effect of embeddedness on trustfulness and trustworthiness

- [x] Frey, V., & Van de Rijt, A. (2016). Arbitrary inequality in reputation systems. Scientific Reports, 6, 38304.

- Do not distinguish between learning and control.

- [ ] Bohnet, I., & Huck, S. (2013). Repetition and reputation: Implications for trust and trustworthiness when institutions change. American Economic Review, 94, 362-366.

- [ ] Bohnet, I., Harmgart, H., Huck, S., & Turan, J.-R. (2005). Learning trust. Journal of the European Economic Assocation, 3, 322-329.

- [ ] Bolton, G. E., Katok, E., Ockenfels, A. (2004) How effective are electronic reputation mechanisms? An experimental investigation. Managerial Science, 50, 1587-1602.

- [ ] DiMaggio, P., & Louch, H. (1998). Socially embedded consumer transactions: For what kinds of purchases do people most often use networks? American Sociological Review, 63, 619-637.

- [ ] Gulati, R., & Gargiulo, M. (1999). Where do interorganizational networks come from? American Journal of Sociology, 104, 1439-1493.

- [ ] Huck, S., Lünser, G. K., & Tyran, J.-R. (2010). Consumer networks and firm reputation: A first experimental investigation. Economic Letters, 108, 242-244.

- [ ] Robinson, D. T., & Stuart, T. E. (2007). Network effects in the governance of strategic alliances. Journal of Law, Economics and Organizations, 23, 242-273.

### Studies that did not find an effect of embeddedness on trust or related cooperative behaviors

- [x] Corten, R., Rosenkranz, S., Buskens, V., & Cook, K. S. (2016). Reputation effects in social networks do not promote cooperation: An experimental test of the Raub & Weesie model. PlosOne, 11, e0155703. 

- [ ] Grujic, J., Fosco, C., Araujo, L., Cuesta, J. A., & Sánchez, A. (2010). Social experimentals in the mesoscale: Humans playing a spatial prisoner's dilemma. PLoS ONE, 5, e13749.

- [ ] Huck, S., Lünser, G. K., & Tyran, J. R. (2012). Competition fosters trust. Games and Economic Behavior, 76, 195-209.

- [x] Van Miltenburg, N., Buskens, V., Raub, W. (2012). Trust in triads: Experience effects. Social Networks, 34, 425-428.

## Control - endogenous

## Control - exogenous

# Dyadic & network embeddedness

## Endogenous dyadic and network embeddedness

## Exogenous dyadic and network embeddedness

- [x] Buskens, V., Raub, W., & Van der Veer, J. (2010). Trust in triads: An experimental study. Social Networks, 32, 301-312.