---
title: "Literature"
author: 
- Thom Volker
date: "`r format(Sys.time(), '%d-%m-%Y')`"
output: 
  html_document:
    theme: spacelab
    highlight: tango
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
bibliography: "/Users/thomvolker/Documents/Master_Thesis/thesis_literature.bib"
csl: "/Users/thomvolker/Documents/styles/apa-6th-edition.csl"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Introduction

## Repeating experiments is not enough

**@munafo2018**

Several studies across many fields estimate that only around $40\%$ of published findings can be replicated reliably. Various funders and communities are promoting ways for independent teams to routinely replicate the findings of others. These efforts are laudable, but insufficient. If a study is skewed and replications recapitulate that approach, findings will be consistently incorrect or biased.

In some cases, routine replication might actually make matters worse. Consistent findings could take on the status of confirmed truths, when they actually reflect failings in study design, methods or analytical tools. Triangulation might be an essential protection against flawed ideas. This is the strategic use of multiple approaches to address one question. Each approach has its own unrelated assumptions, strengths and weaknesses. Results that agree across different methodologies are less likely to be artefacts.

Scientists in today's hyper-competitive environment often lose sight of the need to pursue distinct strands of evidence. The problem was aptly described by William Kaelin, who lamented that the goal of the scientific paper had shiften from testing narrow conclusions in multiple ways to making a broadening series of assertions, each based on limited evidence. Consequently, he said, papers are increasingly like grand mansions of straw, rather than sturdy houses of brick.

**Specious robustness**

We rarely see projects that aim to prove a point from multiple views. Psychology, epidemiology and the clinical sciences are all geared towards producing statistically significant, definitive studies centred on an endpoint that supports a hypothesis. In parts of the biological sciences, a manuscript's acceptance often depends on a 'capstone' study showing animal efficacy, so pursuing that single experiment becomes more important than carefully probing an idea from all directions.

An illuminating example is the oft-observed J-shaped curves that chart correlation between a condition and health outcome. For instance, multiple studies show that people who consume low levels of alcohol are healthier than heavy drinkers and tee-totallers, leading several researchers to conclude that moderate alcohol consumption promotes health. But other factors, such as unhealthy people being advised to give up drinking, would explain the same shape. Similarly, repeated observations that being slightly overweight is associated with the highest life expectancy might be explained by illness (including processes leading up to the manifestation of a disease, which itself can result in reduced weight); by physicians treating overweight individuals more aggressively; and by other favourable characteristics of overweight individuals, such as lower smoking rates.

One example in which triangulation has helped is in establishing that smoking during pregnancy results in babies with lower birth weights. Triangulation means explicitly choosing analytical approaches that depend on different assumptions. For example, if a woman's partner smokes during her pregnancy, many of the same confounders apply as in maternal smoking, but the association with lower birth weight is much weaker. 

**Replication fixation**

Replication has received considerable attention, triangulation has not. Maybe on reason replication has captured to much interest is the often-repeated idea that falsification is at the heart of the scientific enterprise. This idea was popularized by Karl Popper's 1950s maxim that theories can never be proved, only falsified. Yet few experiments, including replication attempts, are explicitly set up to falsify a theory. In fact, we worry that an overemphasis on repeating experiments could provide an unfounded sense of certainty about findings that rely on a single approach. 

Moreover, philosophers of science have moved on since Popper. Better descriptions of how scientists actually work include what epistemologist Peter Lipton called in 1991 "inference to the best explanation", or the search for the "loveliest" explanation. This draws on older ideas that championed abductive over deductive reasoning $-$ looking for likely explanations rather than deriving explanations from first principles. This spirit is also captured in the idea of consilience put forward by polymath William Whewell in the mid-nineteenth century and popularized in the 1990s by naturalist E. O. Wilson. Tis posits that strong theories emerge from the synthesis of multiple lines of evidence, as when Charles Darwin proposed evolution by natural selection.


---


## Triangulation in aetiological epidemiology

**@lawlor_triangulation_2017**

Triangulation refers to the situation in which there is a 'measure' that cannot be (easily) obtained (in aetiological epidemiology) this would be an unbiased causal effect estimate), and you estimate that measure from different locations (in aetiological epidemiology, from different approaches with different sources of bias). The authors propose the following definition of triangulation in aetiological epidemiology:

> The practice of strengthening causal inferences by integrating results from several different approaches, where each approach has different (and assumed to be largely unrelated) key sources of potential bias.

Other commonly used methods of integrating epidemiological evidence, such as independent replication or validation, meta-analysis and systematic reviews, seek to compare (and, in some cases, quantitatively combine) results from the same study design/approach under the assumption that they are all unbiased and estimating the same underlying causal effect. Triangulation aims to integrate data from different methodological approaches with different biases and to exploit these differences to draw qualitative conclusions.

# Methods

# Results

# Conclusion

# Reference list

